spring:
  profiles:
    active: dev


server:
  port: 8080

person:
#  last_name: zsafeaef
  boss: false
  birth: 2019/10/11
  maps: {k1: v1, k2: 12}
  lists:
    - lisi
    - zhaoliu
  Dog:
    name: 小狗
  last-name1: zws
  age: 1
  email: a
